#!/usr/bin/env python3
"""Generate one static localized privacy page from structured legal content."""

from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "Scripts" / "site-privacy-template.html"
REGISTRY_PATH = ROOT / "Scripts" / "site-locales" / "registry.json"
CONTENT_DIR = ROOT / "Scripts" / "site-privacy-locales"
SITE = "https://tumanovnv.github.io/impuls/"
EXPECTED_SECTIONS = ["general", "operator", "data", "purposes", "storage", "third-parties", "rights", "international", "changes"]


def load_registry() -> dict:
    data = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    required = {"code", "label", "path", "privacy_path", "og_locale"}
    locales = data.get("locales", [])
    if not locales or any(required - set(item) for item in locales):
        raise SystemExit("website locale registry entries must include privacy_path")
    paths = [item["privacy_path"] for item in locales]
    if len(paths) != len(set(paths)):
        raise SystemExit("privacy paths must be unique")
    return data


def asset_prefix(path: str) -> str:
    depth = len([part for part in path.split("/") if part])
    return "../" * depth


def build_selector(registry: dict, current: str) -> str:
    links = []
    for item in registry["locales"]:
        current_attr = ' aria-current="page"' if item["code"] == current else ""
        links.append(
            f'<a href="{SITE}{item["privacy_path"]}" hreflang="{html.escape(item["code"])}"{current_attr}>{html.escape(item["label"])}</a>'
        )
    return '<div class="lang" role="group" aria-label="Language / Язык">' + "".join(links) + "</div>"


def render(config: dict, registry: dict) -> str:
    code = config["locale"]
    entry = next((item for item in registry["locales"] if item["code"] == code), None)
    if not entry:
        raise SystemExit(f"locale {code} is not published in registry")
    if config.get("privacy_path") != entry["privacy_path"]:
        raise SystemExit(f"privacy_path mismatch for {code}")
    sections = config.get("sections", [])
    ids = [section.get("id") for section in sections]
    if ids != EXPECTED_SECTIONS:
        raise SystemExit(f"privacy section contract mismatch for {code}: {ids}")
    if len(config.get("toc", [])) != len(EXPECTED_SECTIONS):
        raise SystemExit(f"privacy TOC must have {len(EXPECTED_SECTIONS)} entries for {code}")

    alternate_links = "\n".join(
        f'  <link rel="alternate" hreflang="{html.escape(item["code"])}" href="{SITE}{item["privacy_path"]}">'
        for item in registry["locales"]
    )
    alternate_links += f'\n  <link rel="alternate" hreflang="x-default" href="{SITE}{next(item["privacy_path"] for item in registry["locales"] if item["code"] == registry["default_locale"])}">'

    toc_html = "".join(
        f'<a href="#{html.escape(item["id"])}">{item["label"]}</a>' for item in config["toc"]
    )
    sections_html = "\n".join(
        f'  <section id="{html.escape(section["id"])}">\n    <h2>{section["title"]}</h2>\n{section["html"]}\n  </section>'
        for section in sections
    )

    replacements = {
        "HTML_LANG": config["html_lang"],
        "TITLE": config["title"],
        "DESCRIPTION": config["description"],
        "CANONICAL": SITE + entry["privacy_path"],
        "ALTERNATES": alternate_links,
        "ASSET_PREFIX": asset_prefix(entry["privacy_path"]),
        "BRAND": config["brand"],
        "BACK": config["back"],
        "LANGUAGE_SELECTOR": build_selector(registry, code),
        "EYEBROW": config["eyebrow"],
        "HEADING": config["heading"],
        "LEAD": config["lead"],
        "REVISION": config["revision"],
        "TOC_ARIA": config["toc_aria"],
        "TOC": toc_html,
        "SECTIONS": sections_html,
        "FOOTER_PROJECT": config["footer_project"],
        "FOOTER_SITE": config["footer_site"],
        "FOOTER_SOURCE": config["footer_source"],
    }
    page = TEMPLATE.read_text(encoding="utf-8")
    for key, value in replacements.items():
        page = page.replace("{{" + key + "}}", value)
    if "{{" in page or "}}" in page:
        raise SystemExit(f"unresolved template placeholder for {code}")
    return f'<!-- Generated by Scripts/build-site-privacy-locale.py for {code}. Do not edit directly. -->\n' + page


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--locale", required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    registry = load_registry()
    config_path = CONTENT_DIR / f"{args.locale}.json"
    if not config_path.exists():
        print(f"missing privacy locale: {args.locale}", file=sys.stderr)
        return 2
    config = json.loads(config_path.read_text(encoding="utf-8"))
    if config.get("locale") != args.locale:
        print(f"privacy locale mismatch in {config_path}", file=sys.stderr)
        return 2
    page = render(config, registry)
    entry = next(item for item in registry["locales"] if item["code"] == args.locale)
    target = ROOT / "docs" / entry["privacy_path"] / "index.html"
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != page:
            print(f"{target.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        print(f"{target.relative_to(ROOT)} is current")
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(page, encoding="utf-8")
    print(f"wrote {target.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
