#!/usr/bin/env python3
"""Generate the deterministic Impuls source -> tests -> docs reference map.

The manifest is curated because architectural ownership is a design decision,
while existence and freshness are machine-checked against the repository tree.
Standard-library only so documentation validation adds no project dependency.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "Scripts" / "knowledge-map-manifest.json"
OUTPUT_PATH = ROOT / "knowledge-base" / "12-reference" / "generated-type-test-doc-map.md"


def app_version() -> str:
    for line in (ROOT / "Scripts" / "version").read_text(encoding="utf-8").splitlines():
        if line.startswith("VERSION="):
            value = line.partition("=")[2].strip()
            if value:
                return value
    raise ValueError("Scripts/version does not contain VERSION=")


def load_manifest() -> dict:
    data = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    required = {"documentation_version", "last_reviewed", "entries"}
    missing = required - data.keys()
    if missing:
        raise ValueError(f"manifest missing keys: {', '.join(sorted(missing))}")
    if not isinstance(data["entries"], list) or not data["entries"]:
        raise ValueError("manifest entries must be a non-empty list")
    return data


def relative_link(from_file: Path, target: Path, label: str) -> str:
    relative = os.path.relpath(target, start=from_file.parent).replace(os.sep, "/")
    return f"[{label}]({relative})"


def validated_entries(manifest: dict) -> list[dict]:
    required = {"area", "symbol", "source", "doc", "tests"}
    seen: set[str] = set()
    output: list[dict] = []

    for raw in manifest["entries"]:
        missing = required - raw.keys()
        if missing:
            raise ValueError(
                f"manifest entry {raw.get('symbol', '<unknown>')} missing: "
                + ", ".join(sorted(missing))
            )
        symbol = raw["symbol"]
        if symbol in seen:
            raise ValueError(f"duplicate symbol in manifest: {symbol}")
        seen.add(symbol)

        source = ROOT / raw["source"]
        doc = ROOT / raw["doc"]
        if not source.is_file():
            raise ValueError(f"missing source for {symbol}: {raw['source']}")
        if not doc.is_file():
            raise ValueError(f"missing canonical doc for {symbol}: {raw['doc']}")

        source_text = source.read_text(encoding="utf-8")
        if re.search(rf"\b{re.escape(symbol)}\b", source_text) is None:
            raise ValueError(f"symbol {symbol} is not present in {raw['source']}")

        tests: list[Path] = []
        for test_path in raw["tests"]:
            candidate = ROOT / test_path
            if not candidate.is_file():
                raise ValueError(f"missing test mapping for {symbol}: {test_path}")
            tests.append(candidate)
        if not tests:
            raise ValueError(f"{symbol} has no mapped tests")

        output.append(
            {
                "area": raw["area"],
                "symbol": symbol,
                "source": source,
                "doc": doc,
                "tests": tests,
            }
        )

    return sorted(output, key=lambda item: (item["area"].casefold(), item["symbol"].casefold()))


def render(manifest: dict, entries: list[dict]) -> str:
    lines = [
        "---",
        "title: Generated Type → Tests → Docs Map",
        "type: generated-reference",
        "status: active",
        f"documentation_version: {manifest['documentation_version']}",
        f"app_version: {app_version()}",
        f"last_reviewed: {manifest['last_reviewed']}",
        "tags: [impuls, generated, reference, tests, ai]",
        "---",
        "",
        "# Generated Type → Tests → Docs Map",
        "",
        "> Generated by `Scripts/generate-knowledge-map.py` from `Scripts/knowledge-map-manifest.json`. Do not edit rows by hand.",
        "",
        "This map gives humans and AI agents a deterministic route from an important production type to its source file, mapped verification tests and canonical engineering documentation.",
        "",
        "The manifest is intentionally curated: architectural ownership is a design decision. The generator verifies that every source, symbol, test and document still exists, and CI fails when this committed map is stale.",
        "",
        "| Area | Type | Source | Verification tests | Canonical docs |",
        "| --- | --- | --- | --- | --- |",
    ]

    for entry in entries:
        source = relative_link(OUTPUT_PATH, entry["source"], entry["source"].name)
        doc = relative_link(OUTPUT_PATH, entry["doc"], entry["doc"].name)
        tests = "<br>".join(
            relative_link(OUTPUT_PATH, test, test.name) for test in entry["tests"]
        )
        lines.append(
            f"| {entry['area']} | `{entry['symbol']}` | {source} | {tests} | {doc} |"
        )

    lines += [
        "",
        "## Maintenance contract",
        "",
        "When an important subsystem gains, renames or replaces a core type, update `Scripts/knowledge-map-manifest.json`, run `python3 Scripts/generate-knowledge-map.py`, and commit the generated file in the same change set.",
        "",
        "`python3 Scripts/generate-knowledge-map.py --check` is the CI mode. It does not write files and fails if the generated output differs from the committed reference.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed generated map is stale instead of writing it",
    )
    args = parser.parse_args()

    try:
        manifest = load_manifest()
        entries = validated_entries(manifest)
        expected = render(manifest, entries)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"knowledge map generation failed: {error}", file=sys.stderr)
        return 1

    if args.check:
        if not OUTPUT_PATH.is_file():
            print(f"generated map is missing: {OUTPUT_PATH.relative_to(ROOT)}", file=sys.stderr)
            return 1
        current = OUTPUT_PATH.read_text(encoding="utf-8")
        if current != expected:
            print(
                "generated type/test/doc map is stale; run "
                "python3 Scripts/generate-knowledge-map.py and commit the result",
                file=sys.stderr,
            )
            return 1
        print(f"Knowledge map OK: {len(entries)} core types are mapped and current.")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)} with {len(entries)} core types.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
